#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAE2536227F69F181 (hs@ox.cx)
#
Name     : pypi-hatch_fancy_pypi_readme
Version  : 22.3.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/05/66/6927f8dcb50a0306c86b7f5f597f93a3b9b71ed19280eed180e7004d2d03/hatch_fancy_pypi_readme-22.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/05/66/6927f8dcb50a0306c86b7f5f597f93a3b9b71ed19280eed180e7004d2d03/hatch_fancy_pypi_readme-22.3.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/05/66/6927f8dcb50a0306c86b7f5f597f93a3b9b71ed19280eed180e7004d2d03/hatch_fancy_pypi_readme-22.3.0.tar.gz.asc
Summary  : Fancy PyPI READMEs with Hatch
Group    : Development/Tools
License  : MIT
Requires: pypi-hatch_fancy_pypi_readme-bin = %{version}-%{release}
Requires: pypi-hatch_fancy_pypi_readme-license = %{version}-%{release}
Requires: pypi-hatch_fancy_pypi_readme-python = %{version}-%{release}
Requires: pypi-hatch_fancy_pypi_readme-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
# *hatch-fancy-pypi-readme*
*Because your ✨fancy project✨ deserves a ✨fancy PyPI landing page✨.*

%package bin
Summary: bin components for the pypi-hatch_fancy_pypi_readme package.
Group: Binaries
Requires: pypi-hatch_fancy_pypi_readme-license = %{version}-%{release}

%description bin
bin components for the pypi-hatch_fancy_pypi_readme package.


%package license
Summary: license components for the pypi-hatch_fancy_pypi_readme package.
Group: Default

%description license
license components for the pypi-hatch_fancy_pypi_readme package.


%package python
Summary: python components for the pypi-hatch_fancy_pypi_readme package.
Group: Default
Requires: pypi-hatch_fancy_pypi_readme-python3 = %{version}-%{release}

%description python
python components for the pypi-hatch_fancy_pypi_readme package.


%package python3
Summary: python3 components for the pypi-hatch_fancy_pypi_readme package.
Group: Default
Requires: python3-core
Provides: pypi(hatch_fancy_pypi_readme)
Requires: pypi(hatchling)
Requires: pypi(tomli)

%description python3
python3 components for the pypi-hatch_fancy_pypi_readme package.


%prep
%setup -q -n hatch_fancy_pypi_readme-22.3.0
cd %{_builddir}/hatch_fancy_pypi_readme-22.3.0
pushd ..
cp -a hatch_fancy_pypi_readme-22.3.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661982852
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-hatch_fancy_pypi_readme
cp %{_builddir}/hatch_fancy_pypi_readme-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-hatch_fancy_pypi_readme/fd5e2e6ccd11c0cf3abdefdf45b23b627d15bda6
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hatch-fancy-pypi-readme

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-hatch_fancy_pypi_readme/fd5e2e6ccd11c0cf3abdefdf45b23b627d15bda6

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
